modLoader="javafml"
loaderVersion="[36,)"
license="Academic Free License v3.0"

[[mods]]
modId="obliterum"
version="2.0.3"
displayName="Obliterum"
credits="_CobaltWolf_ for textures. Reynales for some ideas."
displayURL="https://mcreator.net"
authors="Raeis_Eikr"

[[dependencies.obliterum]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




